name: flutterpaytm
description: A new Flutter plugin for Paytm Payment Gateway support with Flutter by Vaibhav Pathak.
version: 1.0.0
homepage: https://github.com/vkpdeveloper/flutterpaytm

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: tk.vkpdeveloper.flutterpaytm
    pluginClass: FlutterpaytmPlugin
